public class test2
{	
	public static void main(String args[])
	{
		try
		{
			int i;
			return;
		}
		catch(Exception e)		
		{
			System.out.print("In Catch Block ");
		}
		finally
		{
			System.out.print("In Finally Block");
		}
	}
}